/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		parameters: { query?: never; header?: never; path?: never; cookie?: never };
		/** Health Check */
		get: operations["get-health"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/pigeons": {
		parameters: { query?: never; header?: never; path?: never; cookie?: never };
		/** List Pigeons */
		get: operations["get-v1-pigeons"];
		put?: never;
		/** Add Pigeon */
		post: operations["post-v1-pigeons"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/pigeons/{id}": {
		parameters: { query?: never; header?: never; path?: never; cookie?: never };
		get?: never;
		put?: never;
		post?: never;
		/** Remove Pigeon */
		delete: operations["delete-v1-pigeons-by-id"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ErrorDetail: {
			/** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
			location?: string;
			/** @description Error message text */
			message?: string;
			/** @description The value at the given location */
			value?: unknown;
		};
		ErrorModel: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/ErrorModel.json
			 */
			readonly $schema?: string;
			/**
			 * @description A human-readable explanation specific to this occurrence of the problem.
			 * @example Property foo is required but is missing.
			 */
			detail?: string;
			/** @description Optional list of individual error details */
			errors?: components["schemas"]["ErrorDetail"][] | null;
			/**
			 * Format: uri
			 * @description A URI reference that identifies the specific occurrence of the problem.
			 * @example https://example.com/error-log/abc123
			 */
			instance?: string;
			/**
			 * Format: int64
			 * @description HTTP status code
			 * @example 400
			 */
			status?: number;
			/**
			 * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
			 * @example Bad Request
			 */
			title?: string;
			/**
			 * Format: uri
			 * @description A URI reference to human-readable documentation for the error.
			 * @default about:blank
			 * @example https://example.com/errors/example
			 */
			type: string;
		};
		HealthStatus: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/HealthStatus.json
			 */
			readonly $schema?: string;
			/**
			 * Format: date-time
			 * @description Build time of the application
			 * @example 2023-01-01T00:00:00Z
			 */
			buildTime: string;
			/**
			 * @description Git commit hash of the application
			 * @example abc123
			 */
			commit: string;
			/**
			 * @description Health status of the application
			 * @example ok
			 */
			status: string;
			/**
			 * Format: date-time
			 * @description Timestamp of the health check
			 * @example 2023-01-01T00:00:00Z
			 */
			timestamp: string;
			/**
			 * @description Uptime of the application in human-readable format
			 * @example 1h0m0s
			 */
			uptime: string;
			/**
			 * @description Version of the application
			 * @example v1.0.0
			 */
			version: string;
		};
		Pigeon: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/Pigeon.json
			 */
			readonly $schema?: string;
			/**
			 * Format: date-time
			 * @description Date when the pigeon was acquired
			 * @example 2023-01-01T00:00:00Z
			 */
			acquiredDate?: string;
			/**
			 * @description Method of acquisition of the pigeon
			 * @enum {string}
			 */
			acquiredVia: "bred" | "purchased" | "gifted" | "captured" | "unknown";
			/**
			 * Format: uuid
			 * @description Unique identifier of the pigeon
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string;
			/**
			 * @description Name of the pigeon
			 * @example Buffy
			 */
			name?: string;
			/**
			 * @description Ring number of the pigeon
			 * @example RN-12345
			 */
			ringNumber?: string;
			/**
			 * @description Sex of the pigeon
			 * @enum {string}
			 */
			sex: "male" | "female" | "unknown";
			/**
			 * @description Confidence level of the sex determination
			 * @enum {string}
			 */
			sexConfidence?: "confirmed" | "presumed";
			/**
			 * @description Status of the pigeon
			 * @enum {string}
			 */
			status: "active" | "deceased" | "sold" | "lost" | "unknown";
		};
		PigeonList: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example https://example.com/schemas/PigeonList.json
			 */
			readonly $schema?: string;
			/** @description List of pigeons */
			pigeons: components["schemas"]["PigeonSummary"][];
			/**
			 * Format: int64
			 * @description Total number of pigeons
			 * @example 100
			 */
			total: number;
		};
		PigeonSummary: {
			/**
			 * Format: date-time
			 * @description Date when the pigeon was acquired
			 * @example 2023-01-01T00:00:00Z
			 */
			acquiredDate?: string;
			/**
			 * @description Method of acquisition of the pigeon
			 * @enum {string}
			 */
			acquiredVia: "bred" | "purchased" | "gifted" | "captured" | "unknown";
			/**
			 * Format: uuid
			 * @description Unique identifier of the pigeon
			 * @example 550e8400-e29b-41d4-a716-446655440000
			 */
			id: string;
			/**
			 * @description Name of the pigeon
			 * @example Buffy
			 */
			name?: string;
			/**
			 * @description Ring number of the pigeon
			 * @example RN-12345
			 */
			ringNumber?: string;
			/**
			 * @description Sex of the pigeon
			 * @enum {string}
			 */
			sex: "male" | "female" | "unknown";
			/**
			 * @description Confidence level of the sex determination
			 * @enum {string}
			 */
			sexConfidence?: "confirmed" | "presumed";
			/**
			 * @description Status of the pigeon
			 * @enum {string}
			 */
			status: "active" | "deceased" | "sold" | "lost" | "unknown";
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type ErrorDetail = components["schemas"]["ErrorDetail"];
export type ErrorModel = components["schemas"]["ErrorModel"];
export type HealthStatus = components["schemas"]["HealthStatus"];
export type Pigeon = components["schemas"]["Pigeon"];
export type PigeonList = components["schemas"]["PigeonList"];
export type PigeonSummary = components["schemas"]["PigeonSummary"];
export type $defs = Record<string, never>;
export interface operations {
	"get-health": {
		parameters: { query?: never; header?: never; path?: never; cookie?: never };
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: { [name: string]: unknown };
				content: { "application/json": components["schemas"]["HealthStatus"] };
			};
			/** @description Error */
			default: {
				headers: { [name: string]: unknown };
				content: { "application/problem+json": components["schemas"]["ErrorModel"] };
			};
		};
	};
	"get-v1-pigeons": {
		parameters: {
			query?: {
				/** @description Page number */
				page?: number;
				/** @description Page size */
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: { [name: string]: unknown };
				content: { "application/json": components["schemas"]["PigeonList"] };
			};
			/** @description Error */
			default: {
				headers: { [name: string]: unknown };
				content: { "application/problem+json": components["schemas"]["ErrorModel"] };
			};
		};
	};
	"post-v1-pigeons": {
		parameters: { query?: never; header?: never; path?: never; cookie?: never };
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: { [name: string]: unknown };
				content: { "application/json": components["schemas"]["Pigeon"] };
			};
			/** @description Error */
			default: {
				headers: { [name: string]: unknown };
				content: { "application/problem+json": components["schemas"]["ErrorModel"] };
			};
		};
	};
	"delete-v1-pigeons-by-id": {
		parameters: { query?: never; header?: never; path: { id: string }; cookie?: never };
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: { headers: { [name: string]: unknown }; content?: never };
			/** @description Error */
			default: {
				headers: { [name: string]: unknown };
				content: { "application/problem+json": components["schemas"]["ErrorModel"] };
			};
		};
	};
}
