# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

dotenv: [.env]

vars:
  AQUA: '{{.AQUA | default "aqua"}}'
  AQUA_ROOT: { sh: "{{.AQUA}} root-dir" }

  CONFIG:
    map:
      WEB: { DOCKER_SERVICE: web, DOCKER_BACKEND: api }
      API:
        DOCKER_SERVICE: api
        DOCKER_BACKEND: postgres
        OPENAPI_SPEC: '{{.API_OPENAPI_SPEC | default "./api/openapi.yml"}}'
      DB: { DOCKER_SERVICE: postgres }

env:
  PATH: '{{.AQUA_ROOT}}/bin:{{.PATH}}'

includes:

  db:
    dir: ./db
    taskfile: ./db/Taskfile.yml

  api:
    dir: ./api
    taskfile: ./api/Taskfile.yml
    vars: { OPENAPI_SPEC: '{{relPath "./api" .API_OPENAPI_SPEC}}' }

  web:
    dir: ./web 
    taskfile: ./web/Taskfile.yml
    vars: { BACKEND_OPENAPI_SPEC: '{{relPath "./web" .API_OPENAPI_SPEC}}' }

tasks:

  # Agents

  agents:skills:sync: 
    desc: Synchronize dependencies
    cmd: { task: "npx:skills:experimental_install" }

  npx:skills:*:
    internal: true
    cmd: "npx skills {{index .MATCH 0}} -y"

  # Docker Commands

  docker:up:
    desc: Start all services in detached mode
    cmd: { task: "docker::detach" }

  docker:stop:
    desc: Stop all services
    cmd: { task: "docker::stop" }

  docker:down:
    desc: Bring down all services
    cmd: { task: "docker::down" }

  docker:logs:
    desc: Follow logs of all services
    cmd: { task: "docker::flogs" }

  docker:ps:
    desc: Show status of all services
    cmd: { task: "docker::ps" }

  docker:*:*:
    internal: true
    label: 'docker:{{if .SERVICE}}{{.SERVICE}}:{{end}}{{.COMMAND}}'
    desc: Run a specific docker command on a specific service
    vars:
      SERVICE: '{{index .MATCH 0}}'
      COMMAND: '{{index .MATCH 1}}'
      DOCKER_COMPOSE: { sh: command -v docker-compose }
      COMMAND_SHORTCUTS:
        map:
          detach: "up -d"
          wait: "up -d --wait"
          flogs: "logs -f"
          clean: "down -v"
      CMD: >-
        {{.DOCKER_COMPOSE | default "docker compose"}}
        {{index .COMMAND_SHORTCUTS .COMMAND | default .COMMAND}}
        {{.SERVICE}}
    cmd: "{{.CMD | trim}}"

  # Service Commands

  db:service:up: &service-up
    desc: Start service in container
    vars: &service-vars
      NAMESPACE: '{{index (splitList ":" .TASK) 0 | upper}}'
      SERVICE: '{{(index .CONFIG .NAMESPACE).DOCKER_SERVICE}}'
    cmd: { task: "docker:{{.SERVICE}}:detach" }

  db:service:logs: &service-logs
    vars: *service-vars
    desc: Follow service container logs
    cmd: { task: "docker:{{.SERVICE}}:flogs" }

  db:service:reset:
    vars: *service-vars
    desc: Reset service container
    cmds:
      - { task: "docker:{{.SERVICE}}:clean" }
      - { task: "docker:{{.SERVICE}}:detach" }

  api:service:up: *service-up
  api:service:logs: *service-logs

  web:service:up: *service-up
  web:service:logs: *service-logs

  api:backend:up: &backend-up
    vars: &backend-vars
      NAMESPACE: '{{index (splitList ":" .TASK) 0 | upper}}'
      BACKEND: '{{(index .CONFIG .NAMESPACE).DOCKER_BACKEND}}'
    desc: Wait for backend container to start
    cmd: { task: "docker:{{.BACKEND}}:detach" }

  api:backend:logs: &backend-logs
    vars: *backend-vars
    desc: Follow backend container logs
    cmd: { task: "docker:{{.BACKEND}}:flogs" }

  api:backend:reset: &backend-reset
    vars: *backend-vars
    desc: Reset backend container
    cmds:
      - { task: "docker:{{.BACKEND}}:clean" }
      - { task: "docker:{{.BACKEND}}:detach" }

  web:backend:up: *backend-up
  web:backend:logs: *backend-logs
