# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [.env]

vars:
  TIMESTAMP: '{{now | date "2006-01-02T15:04:05Z07:00"}}'

  GIT_VERSION: { sh: "git describe --tags --always --dirty" }
  GIT_COMMIT: { sh: "git rev-parse --short HEAD" }

  AQUA: '{{.AQUA | default "aqua"}}'
  AQUA_ROOT: { sh: "{{.AQUA}} root-dir" }

  DOCKER: '{{.DOCKER | default "docker"}}'
  DOCKER_COMPOSE: >-
    {{- $composeCmd := printf "%s compose" .DOCKER -}}
    {{.DOCKER_COMPOSE | default $composeCmd}}

  API_OPENAPI_SPEC: '{{.API_OPENAPI_SPEC | default "./api/openapi.yml"}}'

env:
  PATH: "{{.AQUA_ROOT}}/bin:{{.PATH}}"

includes:
  db:
    dir: ./db
    taskfile: ./db/Taskfile.yml

  api:
    dir: ./api
    taskfile: ./api/Taskfile.yml
    vars:
      BUILD_VERSION: "{{.GIT_VERSION}}"
      BUILD_COMMIT: "{{.GIT_COMMIT}}"
      BUILD_TIMESTAMP: "{{.TIMESTAMP}}"
      OPENAPI_SPEC: '{{relPath "./api" .API_OPENAPI_SPEC}}'

  web:
    dir: ./web
    taskfile: ./web/Taskfile.yml
    vars:
      BACKEND_OPENAPI_SPEC: '{{relPath "./web" .API_OPENAPI_SPEC}}'

tasks:
  # Agents

  skills:sync:
    desc: Synchronize dependencies
    cmd: "npx skills experimental_install -y"

  # Docker

  run:docker:*:*:
    internal: true
    vars:
      ALIASES:
        map:
          detach: up -d
          wait: up -d --wait
          flogs: logs -f
          clean: down -v
      ARGS: >-
        {{- $service := index .MATCH 0 -}}
        {{- $command := index .MATCH 1 -}}
        {{index .ALIASES $command | default $command}} {{$service}}
    cmd: "{{.DOCKER_COMPOSE}} {{.ARGS|trim}}"

  # Docker Commands

  docker:stop:
    desc: Stop services
    cmd: { task: run:docker::stop }

  docker:down:
    desc: Bring down services
    cmd: { task: run:docker::down }

  docker:ps:
    desc: Show status of services
    cmd: { task: run:docker::ps }

  docker:logs:
    desc: Follow logs of services
    cmd: { task: run:docker::flogs }

  # DB / Postgres Service

  docker@db:up:
    desc: Start service in container
    cmd: { task: run:docker:postgres:up }

  docker@db:logs:
    desc: Follow service container logs
    cmd: { task: run:docker:postgres:flogs }

  docker@db:reset:
    desc: Reset container & volumes
    cmds:
      - task: run:docker:postgres:clean
      - task: run:docker:postgres:detach

  # API Service

  docker@api:build:
    desc: Build service container
    vars:
      API_BUILD_VERSION: "{{.GIT_VERSION}}"
      API_BUILD_COMMIT: "{{.GIT_COMMIT}}"
      API_BUILD_BUILD_DATE: "{{.TIMESTAMP}}"
    cmd: { task: run:docker:api:build }

  docker@api:up:
    desc: Start service in container
    cmd: { task: run:docker:api:detach }

  docker@api:logs:
    desc: Follow service container logs
    cmd: { task: run:docker:api:flogs }

  # Web Service

  docker@web:up:
    desc: Start service in container
    cmd: { task: run:docker:web:detach }

  docker@web:logs:
    desc: Follow service container logs
    cmd: { task: run:docker:web:flogs }

  # Meta Commands

  completions:
    desc: Generate shell completions for dev tools
    requires:
      vars:
        - { name: SHELL_TARGET, enum: [bash, zsh] }
        - { name: COMPLETIONS_DIR }
    vars:
      SHELL_TARGET: "{{index .CLI_ARGS_LIST 0}}"
      COMPLETIONS_DIR: "{{index .CLI_ARGS_LIST 1}}"
      FILENAME_FMT: '{{if (eq .SHELL_TARGET "zsh") "_%s" "%s"}}'
      COMMANDS:
        map:
          AQUA: { NAME: aqua, ARGS: "completion {{.SHELL_TARGET}}" }
          TASK: { NAME: task, ARGS: "--completion {{.SHELL_TARGET}}" }
    cmd:
      for: { var: COMMANDS, as: COMMAND }
      cmd: >-
        {{- $cmd  := printf "%s %s" .COMMAND.NAME .COMMAND.ARGS -}}
        {{- $name := printf .FILENAME_FMT .COMMAND.NAME -}}
        {{- $path := joinPath .COMPLETIONS_DIR $name -}}
        {{$cmd}} > {{$path|q}}
