// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/reinielfc/pitch-on-db/apps/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// ParentHandle is an autogenerated mock type for the ParentHandle type
type ParentHandle struct {
	mock.Mock
}

type ParentHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *ParentHandle) EXPECT() *ParentHandle_Expecter {
	return &ParentHandle_Expecter{mock: &_m.Mock}
}

// AssignChild provides a mock function with given fields: ctx, childID
func (_m *ParentHandle) AssignChild(ctx context.Context, childID int64) error {
	ret := _m.Called(ctx, childID)

	if len(ret) == 0 {
		panic("no return value specified for AssignChild")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, childID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ParentHandle_AssignChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignChild'
type ParentHandle_AssignChild_Call struct {
	*mock.Call
}

// AssignChild is a helper method to define mock.On call
//   - ctx context.Context
//   - childID int64
func (_e *ParentHandle_Expecter) AssignChild(ctx interface{}, childID interface{}) *ParentHandle_AssignChild_Call {
	return &ParentHandle_AssignChild_Call{Call: _e.mock.On("AssignChild", ctx, childID)}
}

func (_c *ParentHandle_AssignChild_Call) Run(run func(ctx context.Context, childID int64)) *ParentHandle_AssignChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *ParentHandle_AssignChild_Call) Return(_a0 error) *ParentHandle_AssignChild_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ParentHandle_AssignChild_Call) RunAndReturn(run func(context.Context, int64) error) *ParentHandle_AssignChild_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function with given fields: ctx
func (_m *ParentHandle) GetChildren(ctx context.Context) ([]domain.Pigeon, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []domain.Pigeon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Pigeon, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Pigeon); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Pigeon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParentHandle_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type ParentHandle_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ParentHandle_Expecter) GetChildren(ctx interface{}) *ParentHandle_GetChildren_Call {
	return &ParentHandle_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx)}
}

func (_c *ParentHandle_GetChildren_Call) Run(run func(ctx context.Context)) *ParentHandle_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ParentHandle_GetChildren_Call) Return(_a0 []domain.Pigeon, _a1 error) *ParentHandle_GetChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParentHandle_GetChildren_Call) RunAndReturn(run func(context.Context) ([]domain.Pigeon, error)) *ParentHandle_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// HasChildren provides a mock function with given fields: ctx
func (_m *ParentHandle) HasChildren(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HasChildren")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParentHandle_HasChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasChildren'
type ParentHandle_HasChildren_Call struct {
	*mock.Call
}

// HasChildren is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ParentHandle_Expecter) HasChildren(ctx interface{}) *ParentHandle_HasChildren_Call {
	return &ParentHandle_HasChildren_Call{Call: _e.mock.On("HasChildren", ctx)}
}

func (_c *ParentHandle_HasChildren_Call) Run(run func(ctx context.Context)) *ParentHandle_HasChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ParentHandle_HasChildren_Call) Return(_a0 bool, _a1 error) *ParentHandle_HasChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParentHandle_HasChildren_Call) RunAndReturn(run func(context.Context) (bool, error)) *ParentHandle_HasChildren_Call {
	_c.Call.Return(run)
	return _c
}

// NewParentHandle creates a new instance of ParentHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParentHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParentHandle {
	mock := &ParentHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
