// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/reinielfc/pitch-on-db/apps/api/domain"

	mock "github.com/stretchr/testify/mock"
)

// PigeonRepository is an autogenerated mock type for the PigeonRepository type
type PigeonRepository struct {
	mock.Mock
}

type PigeonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PigeonRepository) EXPECT() *PigeonRepository_Expecter {
	return &PigeonRepository_Expecter{mock: &_m.Mock}
}

// AssignChild provides a mock function with given fields: ctx, parentID, childID
func (_m *PigeonRepository) AssignChild(ctx context.Context, parentID int64, childID int64) error {
	ret := _m.Called(ctx, parentID, childID)

	if len(ret) == 0 {
		panic("no return value specified for AssignChild")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, parentID, childID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PigeonRepository_AssignChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignChild'
type PigeonRepository_AssignChild_Call struct {
	*mock.Call
}

// AssignChild is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
//   - childID int64
func (_e *PigeonRepository_Expecter) AssignChild(ctx interface{}, parentID interface{}, childID interface{}) *PigeonRepository_AssignChild_Call {
	return &PigeonRepository_AssignChild_Call{Call: _e.mock.On("AssignChild", ctx, parentID, childID)}
}

func (_c *PigeonRepository_AssignChild_Call) Run(run func(ctx context.Context, parentID int64, childID int64)) *PigeonRepository_AssignChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *PigeonRepository_AssignChild_Call) Return(_a0 error) *PigeonRepository_AssignChild_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PigeonRepository_AssignChild_Call) RunAndReturn(run func(context.Context, int64, int64) error) *PigeonRepository_AssignChild_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, pigeon
func (_m *PigeonRepository) Create(ctx context.Context, pigeon domain.Pigeon) (domain.Pigeon, error) {
	ret := _m.Called(ctx, pigeon)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Pigeon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pigeon) (domain.Pigeon, error)); ok {
		return rf(ctx, pigeon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Pigeon) domain.Pigeon); ok {
		r0 = rf(ctx, pigeon)
	} else {
		r0 = ret.Get(0).(domain.Pigeon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Pigeon) error); ok {
		r1 = rf(ctx, pigeon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PigeonRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pigeon domain.Pigeon
func (_e *PigeonRepository_Expecter) Create(ctx interface{}, pigeon interface{}) *PigeonRepository_Create_Call {
	return &PigeonRepository_Create_Call{Call: _e.mock.On("Create", ctx, pigeon)}
}

func (_c *PigeonRepository_Create_Call) Run(run func(ctx context.Context, pigeon domain.Pigeon)) *PigeonRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Pigeon))
	})
	return _c
}

func (_c *PigeonRepository_Create_Call) Return(_a0 domain.Pigeon, _a1 error) *PigeonRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_Create_Call) RunAndReturn(run func(context.Context, domain.Pigeon) (domain.Pigeon, error)) *PigeonRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PigeonRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PigeonRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PigeonRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PigeonRepository_Expecter) Delete(ctx interface{}, id interface{}) *PigeonRepository_Delete_Call {
	return &PigeonRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *PigeonRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *PigeonRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PigeonRepository_Delete_Call) Return(_a0 error) *PigeonRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PigeonRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *PigeonRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, id
func (_m *PigeonRepository) Exists(ctx context.Context, id int64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type PigeonRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PigeonRepository_Expecter) Exists(ctx interface{}, id interface{}) *PigeonRepository_Exists_Call {
	return &PigeonRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *PigeonRepository_Exists_Call) Run(run func(ctx context.Context, id int64)) *PigeonRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PigeonRepository_Exists_Call) Return(_a0 bool, _a1 error) *PigeonRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_Exists_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *PigeonRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *PigeonRepository) Get(ctx context.Context, id int64) (*domain.Pigeon, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Pigeon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Pigeon, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Pigeon); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Pigeon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PigeonRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PigeonRepository_Expecter) Get(ctx interface{}, id interface{}) *PigeonRepository_Get_Call {
	return &PigeonRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *PigeonRepository_Get_Call) Run(run func(ctx context.Context, id int64)) *PigeonRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PigeonRepository_Get_Call) Return(_a0 *domain.Pigeon, _a1 error) *PigeonRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_Get_Call) RunAndReturn(run func(context.Context, int64) (*domain.Pigeon, error)) *PigeonRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function with given fields: ctx, parentID
func (_m *PigeonRepository) GetChildren(ctx context.Context, parentID int64) ([]domain.Pigeon, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []domain.Pigeon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Pigeon, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Pigeon); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Pigeon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type PigeonRepository_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
func (_e *PigeonRepository_Expecter) GetChildren(ctx interface{}, parentID interface{}) *PigeonRepository_GetChildren_Call {
	return &PigeonRepository_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, parentID)}
}

func (_c *PigeonRepository_GetChildren_Call) Run(run func(ctx context.Context, parentID int64)) *PigeonRepository_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PigeonRepository_GetChildren_Call) Return(_a0 []domain.Pigeon, _a1 error) *PigeonRepository_GetChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_GetChildren_Call) RunAndReturn(run func(context.Context, int64) ([]domain.Pigeon, error)) *PigeonRepository_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetParents provides a mock function with given fields: ctx, childID
func (_m *PigeonRepository) GetParents(ctx context.Context, childID int64) (*domain.PigeonParents, error) {
	ret := _m.Called(ctx, childID)

	if len(ret) == 0 {
		panic("no return value specified for GetParents")
	}

	var r0 *domain.PigeonParents
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.PigeonParents, error)); ok {
		return rf(ctx, childID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.PigeonParents); ok {
		r0 = rf(ctx, childID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PigeonParents)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, childID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_GetParents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParents'
type PigeonRepository_GetParents_Call struct {
	*mock.Call
}

// GetParents is a helper method to define mock.On call
//   - ctx context.Context
//   - childID int64
func (_e *PigeonRepository_Expecter) GetParents(ctx interface{}, childID interface{}) *PigeonRepository_GetParents_Call {
	return &PigeonRepository_GetParents_Call{Call: _e.mock.On("GetParents", ctx, childID)}
}

func (_c *PigeonRepository_GetParents_Call) Run(run func(ctx context.Context, childID int64)) *PigeonRepository_GetParents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PigeonRepository_GetParents_Call) Return(_a0 *domain.PigeonParents, _a1 error) *PigeonRepository_GetParents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_GetParents_Call) RunAndReturn(run func(context.Context, int64) (*domain.PigeonParents, error)) *PigeonRepository_GetParents_Call {
	_c.Call.Return(run)
	return _c
}

// HasChildren provides a mock function with given fields: ctx, parentID
func (_m *PigeonRepository) HasChildren(ctx context.Context, parentID int64) (bool, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for HasChildren")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, parentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_HasChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasChildren'
type PigeonRepository_HasChildren_Call struct {
	*mock.Call
}

// HasChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
func (_e *PigeonRepository_Expecter) HasChildren(ctx interface{}, parentID interface{}) *PigeonRepository_HasChildren_Call {
	return &PigeonRepository_HasChildren_Call{Call: _e.mock.On("HasChildren", ctx, parentID)}
}

func (_c *PigeonRepository_HasChildren_Call) Run(run func(ctx context.Context, parentID int64)) *PigeonRepository_HasChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PigeonRepository_HasChildren_Call) Return(_a0 bool, _a1 error) *PigeonRepository_HasChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_HasChildren_Call) RunAndReturn(run func(context.Context, int64) (bool, error)) *PigeonRepository_HasChildren_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *PigeonRepository) ListAll(ctx context.Context) ([]domain.Pigeon, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []domain.Pigeon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Pigeon, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Pigeon); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Pigeon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type PigeonRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PigeonRepository_Expecter) ListAll(ctx interface{}) *PigeonRepository_ListAll_Call {
	return &PigeonRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *PigeonRepository_ListAll_Call) Run(run func(ctx context.Context)) *PigeonRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PigeonRepository_ListAll_Call) Return(_a0 []domain.Pigeon, _a1 error) *PigeonRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_ListAll_Call) RunAndReturn(run func(context.Context) ([]domain.Pigeon, error)) *PigeonRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, pigeonPatch
func (_m *PigeonRepository) Update(ctx context.Context, id int64, pigeonPatch domain.PigeonPatch) (domain.Pigeon, error) {
	ret := _m.Called(ctx, id, pigeonPatch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Pigeon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.PigeonPatch) (domain.Pigeon, error)); ok {
		return rf(ctx, id, pigeonPatch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.PigeonPatch) domain.Pigeon); ok {
		r0 = rf(ctx, id, pigeonPatch)
	} else {
		r0 = ret.Get(0).(domain.Pigeon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.PigeonPatch) error); ok {
		r1 = rf(ctx, id, pigeonPatch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PigeonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type PigeonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - pigeonPatch domain.PigeonPatch
func (_e *PigeonRepository_Expecter) Update(ctx interface{}, id interface{}, pigeonPatch interface{}) *PigeonRepository_Update_Call {
	return &PigeonRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, pigeonPatch)}
}

func (_c *PigeonRepository_Update_Call) Run(run func(ctx context.Context, id int64, pigeonPatch domain.PigeonPatch)) *PigeonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.PigeonPatch))
	})
	return _c
}

func (_c *PigeonRepository_Update_Call) Return(_a0 domain.Pigeon, _a1 error) *PigeonRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PigeonRepository_Update_Call) RunAndReturn(run func(context.Context, int64, domain.PigeonPatch) (domain.Pigeon, error)) *PigeonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewPigeonRepository creates a new instance of PigeonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPigeonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PigeonRepository {
	mock := &PigeonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
