// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TagRepository is an autogenerated mock type for the TagRepository type
type TagRepository struct {
	mock.Mock
}

type TagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TagRepository) EXPECT() *TagRepository_Expecter {
	return &TagRepository_Expecter{mock: &_m.Mock}
}

// GetPigeonTags provides a mock function with given fields: ctx, pigeonID
func (_m *TagRepository) GetPigeonTags(ctx context.Context, pigeonID int64) ([]string, error) {
	ret := _m.Called(ctx, pigeonID)

	if len(ret) == 0 {
		panic("no return value specified for GetPigeonTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return rf(ctx, pigeonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = rf(ctx, pigeonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, pigeonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepository_GetPigeonTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPigeonTags'
type TagRepository_GetPigeonTags_Call struct {
	*mock.Call
}

// GetPigeonTags is a helper method to define mock.On call
//   - ctx context.Context
//   - pigeonID int64
func (_e *TagRepository_Expecter) GetPigeonTags(ctx interface{}, pigeonID interface{}) *TagRepository_GetPigeonTags_Call {
	return &TagRepository_GetPigeonTags_Call{Call: _e.mock.On("GetPigeonTags", ctx, pigeonID)}
}

func (_c *TagRepository_GetPigeonTags_Call) Run(run func(ctx context.Context, pigeonID int64)) *TagRepository_GetPigeonTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TagRepository_GetPigeonTags_Call) Return(_a0 []string, _a1 error) *TagRepository_GetPigeonTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepository_GetPigeonTags_Call) RunAndReturn(run func(context.Context, int64) ([]string, error)) *TagRepository_GetPigeonTags_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *TagRepository) List(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TagRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TagRepository_Expecter) List(ctx interface{}) *TagRepository_List_Call {
	return &TagRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *TagRepository_List_Call) Run(run func(ctx context.Context)) *TagRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TagRepository_List_Call) Return(_a0 []string, _a1 error) *TagRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepository_List_Call) RunAndReturn(run func(context.Context) ([]string, error)) *TagRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// PruneOrphanedTags provides a mock function with given fields: ctx
func (_m *TagRepository) PruneOrphanedTags(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PruneOrphanedTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepository_PruneOrphanedTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneOrphanedTags'
type TagRepository_PruneOrphanedTags_Call struct {
	*mock.Call
}

// PruneOrphanedTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TagRepository_Expecter) PruneOrphanedTags(ctx interface{}) *TagRepository_PruneOrphanedTags_Call {
	return &TagRepository_PruneOrphanedTags_Call{Call: _e.mock.On("PruneOrphanedTags", ctx)}
}

func (_c *TagRepository_PruneOrphanedTags_Call) Run(run func(ctx context.Context)) *TagRepository_PruneOrphanedTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TagRepository_PruneOrphanedTags_Call) Return(_a0 error) *TagRepository_PruneOrphanedTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepository_PruneOrphanedTags_Call) RunAndReturn(run func(context.Context) error) *TagRepository_PruneOrphanedTags_Call {
	_c.Call.Return(run)
	return _c
}

// SetPigeonTags provides a mock function with given fields: ctx, pigeonID, tags
func (_m *TagRepository) SetPigeonTags(ctx context.Context, pigeonID int64, tags []string) error {
	ret := _m.Called(ctx, pigeonID, tags)

	if len(ret) == 0 {
		panic("no return value specified for SetPigeonTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []string) error); ok {
		r0 = rf(ctx, pigeonID, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepository_SetPigeonTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPigeonTags'
type TagRepository_SetPigeonTags_Call struct {
	*mock.Call
}

// SetPigeonTags is a helper method to define mock.On call
//   - ctx context.Context
//   - pigeonID int64
//   - tags []string
func (_e *TagRepository_Expecter) SetPigeonTags(ctx interface{}, pigeonID interface{}, tags interface{}) *TagRepository_SetPigeonTags_Call {
	return &TagRepository_SetPigeonTags_Call{Call: _e.mock.On("SetPigeonTags", ctx, pigeonID, tags)}
}

func (_c *TagRepository_SetPigeonTags_Call) Run(run func(ctx context.Context, pigeonID int64, tags []string)) *TagRepository_SetPigeonTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]string))
	})
	return _c
}

func (_c *TagRepository_SetPigeonTags_Call) Return(_a0 error) *TagRepository_SetPigeonTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepository_SetPigeonTags_Call) RunAndReturn(run func(context.Context, int64, []string) error) *TagRepository_SetPigeonTags_Call {
	_c.Call.Return(run)
	return _c
}

// NewTagRepository creates a new instance of TagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagRepository {
	mock := &TagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
