// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pigeons.sql

package repository

import (
	"context"
	"time"
)

const createPigeon = `-- name: CreatePigeon :one
INSERT INTO pigeons (name, band_number, birth_date, sex)
VALUES ($1, $2, $3, $4)
RETURNING id, name, band_number, birth_date, sex, created_at
`

type CreatePigeonParams struct {
	Name       string
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
}

type CreatePigeonRow struct {
	ID         int64
	Name       string
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
	CreatedAt  time.Time
}

func (q *Queries) CreatePigeon(ctx context.Context, arg CreatePigeonParams) (CreatePigeonRow, error) {
	row := q.db.QueryRowContext(ctx, createPigeon,
		arg.Name,
		arg.BandNumber,
		arg.BirthDate,
		arg.Sex,
	)
	var i CreatePigeonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BandNumber,
		&i.BirthDate,
		&i.Sex,
		&i.CreatedAt,
	)
	return i, err
}

const deletePigeon = `-- name: DeletePigeon :exec
DELETE FROM pigeons
WHERE id = $1
`

func (q *Queries) DeletePigeon(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePigeon, id)
	return err
}

const getPigeon = `-- name: GetPigeon :one
SELECT id, name, band_number, birth_date, sex, created_at
FROM pigeons
WHERE id = $1
`

type GetPigeonRow struct {
	ID         int64
	Name       string
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
	CreatedAt  time.Time
}

func (q *Queries) GetPigeon(ctx context.Context, id int64) (GetPigeonRow, error) {
	row := q.db.QueryRowContext(ctx, getPigeon, id)
	var i GetPigeonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BandNumber,
		&i.BirthDate,
		&i.Sex,
		&i.CreatedAt,
	)
	return i, err
}

const listPigeons = `-- name: ListPigeons :many
SELECT id, name, band_number, birth_date, sex, created_at
FROM pigeons
ORDER BY id
`

type ListPigeonsRow struct {
	ID         int64
	Name       string
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
	CreatedAt  time.Time
}

func (q *Queries) ListPigeons(ctx context.Context) ([]ListPigeonsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPigeons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPigeonsRow
	for rows.Next() {
		var i ListPigeonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BandNumber,
			&i.BirthDate,
			&i.Sex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePigeon = `-- name: UpdatePigeon :one
UPDATE pigeons
SET
    name        = COALESCE($1, name),
    band_number = CASE WHEN $2::bool THEN $3 ELSE band_number END,
    birth_date  = CASE WHEN $4::bool THEN $5 ELSE birth_date END,
    sex         = CASE WHEN $6::bool THEN $7 ELSE sex END
WHERE id = $8
RETURNING id, name, band_number, birth_date, sex, created_at
`

type UpdatePigeonParams struct {
	Name          *string
	SetBandNumber bool
	BandNumber    *string
	SetBirthDate  bool
	BirthDate     *time.Time
	SetSex        bool
	Sex           *string
	ID            int64
}

type UpdatePigeonRow struct {
	ID         int64
	Name       string
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
	CreatedAt  time.Time
}

func (q *Queries) UpdatePigeon(ctx context.Context, arg UpdatePigeonParams) (UpdatePigeonRow, error) {
	row := q.db.QueryRowContext(ctx, updatePigeon,
		arg.Name,
		arg.SetBandNumber,
		arg.BandNumber,
		arg.SetBirthDate,
		arg.BirthDate,
		arg.SetSex,
		arg.Sex,
		arg.ID,
	)
	var i UpdatePigeonRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BandNumber,
		&i.BirthDate,
		&i.Sex,
		&i.CreatedAt,
	)
	return i, err
}
