// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package repository

import (
	"context"
)

const addPigeonTag = `-- name: AddPigeonTag :exec
INSERT INTO pigeon_tags (pigeon_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPigeonTagParams struct {
	PigeonID int64
	TagID    int64
}

func (q *Queries) AddPigeonTag(ctx context.Context, arg AddPigeonTagParams) error {
	_, err := q.db.ExecContext(ctx, addPigeonTag, arg.PigeonID, arg.TagID)
	return err
}

const clearPigeonTags = `-- name: ClearPigeonTags :exec
DELETE FROM pigeon_tags
WHERE pigeon_id = $1
`

func (q *Queries) ClearPigeonTags(ctx context.Context, pigeonID int64) error {
	_, err := q.db.ExecContext(ctx, clearPigeonTags, pigeonID)
	return err
}

const getPigeonTags = `-- name: GetPigeonTags :many
SELECT t.id, t.name
FROM tags t
JOIN pigeon_tags pt ON pt.tag_id = t.id
WHERE pt.pigeon_id = $1
ORDER BY t.name
`

func (q *Queries) GetPigeonTags(ctx context.Context, pigeonID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getPigeonTags, pigeonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePigeonTag = `-- name: RemovePigeonTag :exec
DELETE FROM pigeon_tags
WHERE pigeon_id = $1
  AND tag_id = (SELECT id FROM tags WHERE name = $2)
`

type RemovePigeonTagParams struct {
	PigeonID int64
	Name     string
}

func (q *Queries) RemovePigeonTag(ctx context.Context, arg RemovePigeonTagParams) error {
	_, err := q.db.ExecContext(ctx, removePigeonTag, arg.PigeonID, arg.Name)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) UpsertTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
