// Code generated by "enumer -type=AppEnv -trimprefix=AppEnv -transform=snake -values -output=options_enumer.go"; DO NOT EDIT.

package config

import (
	"fmt"
	"strings"
)

const _AppEnvName = "devprod"

var _AppEnvIndex = [...]uint8{0, 3, 7}

const _AppEnvLowerName = "devprod"

func (i AppEnv) String() string {
	if i < 0 || i >= AppEnv(len(_AppEnvIndex)-1) {
		return fmt.Sprintf("AppEnv(%d)", i)
	}
	return _AppEnvName[_AppEnvIndex[i]:_AppEnvIndex[i+1]]
}

func (AppEnv) Values() []string {
	return AppEnvStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AppEnvNoOp() {
	var x [1]struct{}
	_ = x[AppEnvDev-(0)]
	_ = x[AppEnvProd-(1)]
}

var _AppEnvValues = []AppEnv{AppEnvDev, AppEnvProd}

var _AppEnvNameToValueMap = map[string]AppEnv{
	_AppEnvName[0:3]:      AppEnvDev,
	_AppEnvLowerName[0:3]: AppEnvDev,
	_AppEnvName[3:7]:      AppEnvProd,
	_AppEnvLowerName[3:7]: AppEnvProd,
}

var _AppEnvNames = []string{
	_AppEnvName[0:3],
	_AppEnvName[3:7],
}

// AppEnvString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AppEnvString(s string) (AppEnv, error) {
	if val, ok := _AppEnvNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AppEnvNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AppEnv values", s)
}

// AppEnvValues returns all values of the enum
func AppEnvValues() []AppEnv {
	return _AppEnvValues
}

// AppEnvStrings returns a slice of all String values of the enum
func AppEnvStrings() []string {
	strs := make([]string, len(_AppEnvNames))
	copy(strs, _AppEnvNames)
	return strs
}

// IsAAppEnv returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AppEnv) IsAAppEnv() bool {
	for _, v := range _AppEnvValues {
		if i == v {
			return true
		}
	}
	return false
}
