// Code generated by "enumer -type=Sex,SexConfidence,Status,AcquisitionMethod -trimprefix=SexConfidence,Sex,Status,AcquisitionMethod -transform=snake -values -output=domain_enumer.go"; DO NOT EDIT.

package pigeon

import (
	"fmt"
	"strings"
)

const _SexName = "malefemaleunknown"

var _SexIndex = [...]uint8{0, 4, 10, 17}

const _SexLowerName = "malefemaleunknown"

func (i Sex) String() string {
	if i < 0 || i >= Sex(len(_SexIndex)-1) {
		return fmt.Sprintf("Sex(%d)", i)
	}
	return _SexName[_SexIndex[i]:_SexIndex[i+1]]
}

func (Sex) Values() []string {
	return SexStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SexNoOp() {
	var x [1]struct{}
	_ = x[SexMale-(0)]
	_ = x[SexFemale-(1)]
	_ = x[SexUnknown-(2)]
}

var _SexValues = []Sex{SexMale, SexFemale, SexUnknown}

var _SexNameToValueMap = map[string]Sex{
	_SexName[0:4]:        SexMale,
	_SexLowerName[0:4]:   SexMale,
	_SexName[4:10]:       SexFemale,
	_SexLowerName[4:10]:  SexFemale,
	_SexName[10:17]:      SexUnknown,
	_SexLowerName[10:17]: SexUnknown,
}

var _SexNames = []string{
	_SexName[0:4],
	_SexName[4:10],
	_SexName[10:17],
}

// SexString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SexString(s string) (Sex, error) {
	if val, ok := _SexNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SexNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Sex values", s)
}

// SexValues returns all values of the enum
func SexValues() []Sex {
	return _SexValues
}

// SexStrings returns a slice of all String values of the enum
func SexStrings() []string {
	strs := make([]string, len(_SexNames))
	copy(strs, _SexNames)
	return strs
}

// IsASex returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Sex) IsASex() bool {
	for _, v := range _SexValues {
		if i == v {
			return true
		}
	}
	return false
}

const _SexConfidenceName = "confirmedpresumed"

var _SexConfidenceIndex = [...]uint8{0, 9, 17}

const _SexConfidenceLowerName = "confirmedpresumed"

func (i SexConfidence) String() string {
	if i < 0 || i >= SexConfidence(len(_SexConfidenceIndex)-1) {
		return fmt.Sprintf("SexConfidence(%d)", i)
	}
	return _SexConfidenceName[_SexConfidenceIndex[i]:_SexConfidenceIndex[i+1]]
}

func (SexConfidence) Values() []string {
	return SexConfidenceStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SexConfidenceNoOp() {
	var x [1]struct{}
	_ = x[SexConfidenceConfirmed-(0)]
	_ = x[SexConfidencePresumed-(1)]
}

var _SexConfidenceValues = []SexConfidence{SexConfidenceConfirmed, SexConfidencePresumed}

var _SexConfidenceNameToValueMap = map[string]SexConfidence{
	_SexConfidenceName[0:9]:       SexConfidenceConfirmed,
	_SexConfidenceLowerName[0:9]:  SexConfidenceConfirmed,
	_SexConfidenceName[9:17]:      SexConfidencePresumed,
	_SexConfidenceLowerName[9:17]: SexConfidencePresumed,
}

var _SexConfidenceNames = []string{
	_SexConfidenceName[0:9],
	_SexConfidenceName[9:17],
}

// SexConfidenceString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SexConfidenceString(s string) (SexConfidence, error) {
	if val, ok := _SexConfidenceNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SexConfidenceNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SexConfidence values", s)
}

// SexConfidenceValues returns all values of the enum
func SexConfidenceValues() []SexConfidence {
	return _SexConfidenceValues
}

// SexConfidenceStrings returns a slice of all String values of the enum
func SexConfidenceStrings() []string {
	strs := make([]string, len(_SexConfidenceNames))
	copy(strs, _SexConfidenceNames)
	return strs
}

// IsASexConfidence returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SexConfidence) IsASexConfidence() bool {
	for _, v := range _SexConfidenceValues {
		if i == v {
			return true
		}
	}
	return false
}

const _StatusName = "activedeceasedsoldlostunknown"

var _StatusIndex = [...]uint8{0, 6, 14, 18, 22, 29}

const _StatusLowerName = "activedeceasedsoldlostunknown"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

func (Status) Values() []string {
	return StatusStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusActive-(0)]
	_ = x[StatusDeceased-(1)]
	_ = x[StatusSold-(2)]
	_ = x[StatusLost-(3)]
	_ = x[StatusUnknown-(4)]
}

var _StatusValues = []Status{StatusActive, StatusDeceased, StatusSold, StatusLost, StatusUnknown}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:6]:        StatusActive,
	_StatusLowerName[0:6]:   StatusActive,
	_StatusName[6:14]:       StatusDeceased,
	_StatusLowerName[6:14]:  StatusDeceased,
	_StatusName[14:18]:      StatusSold,
	_StatusLowerName[14:18]: StatusSold,
	_StatusName[18:22]:      StatusLost,
	_StatusLowerName[18:22]: StatusLost,
	_StatusName[22:29]:      StatusUnknown,
	_StatusLowerName[22:29]: StatusUnknown,
}

var _StatusNames = []string{
	_StatusName[0:6],
	_StatusName[6:14],
	_StatusName[14:18],
	_StatusName[18:22],
	_StatusName[22:29],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

const _AcquisitionMethodName = "bredpurchasedgiftedcapturedunknown"

var _AcquisitionMethodIndex = [...]uint8{0, 4, 13, 19, 27, 34}

const _AcquisitionMethodLowerName = "bredpurchasedgiftedcapturedunknown"

func (i AcquisitionMethod) String() string {
	if i < 0 || i >= AcquisitionMethod(len(_AcquisitionMethodIndex)-1) {
		return fmt.Sprintf("AcquisitionMethod(%d)", i)
	}
	return _AcquisitionMethodName[_AcquisitionMethodIndex[i]:_AcquisitionMethodIndex[i+1]]
}

func (AcquisitionMethod) Values() []string {
	return AcquisitionMethodStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AcquisitionMethodNoOp() {
	var x [1]struct{}
	_ = x[AcquisitionMethodBred-(0)]
	_ = x[AcquisitionMethodPurchased-(1)]
	_ = x[AcquisitionMethodGifted-(2)]
	_ = x[AcquisitionMethodCaptured-(3)]
	_ = x[AcquisitionMethodUnknown-(4)]
}

var _AcquisitionMethodValues = []AcquisitionMethod{AcquisitionMethodBred, AcquisitionMethodPurchased, AcquisitionMethodGifted, AcquisitionMethodCaptured, AcquisitionMethodUnknown}

var _AcquisitionMethodNameToValueMap = map[string]AcquisitionMethod{
	_AcquisitionMethodName[0:4]:        AcquisitionMethodBred,
	_AcquisitionMethodLowerName[0:4]:   AcquisitionMethodBred,
	_AcquisitionMethodName[4:13]:       AcquisitionMethodPurchased,
	_AcquisitionMethodLowerName[4:13]:  AcquisitionMethodPurchased,
	_AcquisitionMethodName[13:19]:      AcquisitionMethodGifted,
	_AcquisitionMethodLowerName[13:19]: AcquisitionMethodGifted,
	_AcquisitionMethodName[19:27]:      AcquisitionMethodCaptured,
	_AcquisitionMethodLowerName[19:27]: AcquisitionMethodCaptured,
	_AcquisitionMethodName[27:34]:      AcquisitionMethodUnknown,
	_AcquisitionMethodLowerName[27:34]: AcquisitionMethodUnknown,
}

var _AcquisitionMethodNames = []string{
	_AcquisitionMethodName[0:4],
	_AcquisitionMethodName[4:13],
	_AcquisitionMethodName[13:19],
	_AcquisitionMethodName[19:27],
	_AcquisitionMethodName[27:34],
}

// AcquisitionMethodString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AcquisitionMethodString(s string) (AcquisitionMethod, error) {
	if val, ok := _AcquisitionMethodNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AcquisitionMethodNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AcquisitionMethod values", s)
}

// AcquisitionMethodValues returns all values of the enum
func AcquisitionMethodValues() []AcquisitionMethod {
	return _AcquisitionMethodValues
}

// AcquisitionMethodStrings returns a slice of all String values of the enum
func AcquisitionMethodStrings() []string {
	strs := make([]string, len(_AcquisitionMethodNames))
	copy(strs, _AcquisitionMethodNames)
	return strs
}

// IsAAcquisitionMethod returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AcquisitionMethod) IsAAcquisitionMethod() bool {
	for _, v := range _AcquisitionMethodValues {
		if i == v {
			return true
		}
	}
	return false
}
