// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pigeons.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const checkPigeonExists = `-- name: CheckPigeonExists :one
SELECT EXISTS (
    SELECT 1
    FROM pigeons
    WHERE id = $1
)
`

func (q *Queries) CheckPigeonExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPigeonExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPigeonHasChildrenAsFather = `-- name: CheckPigeonHasChildrenAsFather :one
SELECT EXISTS (
    SELECT 1
    FROM pigeons
    WHERE father_id = $1
)
`

func (q *Queries) CheckPigeonHasChildrenAsFather(ctx context.Context, fatherID sql.NullInt64) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPigeonHasChildrenAsFather, fatherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPigeonHasChildrenAsMother = `-- name: CheckPigeonHasChildrenAsMother :one
SELECT EXISTS (
    SELECT 1
    FROM pigeons
    WHERE mother_id = $1
)
`

func (q *Queries) CheckPigeonHasChildrenAsMother(ctx context.Context, motherID sql.NullInt64) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkPigeonHasChildrenAsMother, motherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPigeon = `-- name: CreatePigeon :one
INSERT INTO pigeons (name, birth_date, sex, properties)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, birth_date, sex, father_id, mother_id, properties
`

type CreatePigeonParams struct {
	Name       string
	BirthDate  *time.Time
	Sex        *string
	Properties *json.RawMessage
}

func (q *Queries) CreatePigeon(ctx context.Context, arg CreatePigeonParams) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, createPigeon,
		arg.Name,
		arg.BirthDate,
		arg.Sex,
		arg.Properties,
	)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BirthDate,
		&i.Sex,
		&i.FatherID,
		&i.MotherID,
		&i.Properties,
	)
	return i, err
}

const deletePigeon = `-- name: DeletePigeon :exec
DELETE FROM pigeons WHERE id = $1
`

func (q *Queries) DeletePigeon(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePigeon, id)
	return err
}

const getPigeon = `-- name: GetPigeon :one
SELECT id, name, created_at, birth_date, sex, father_id, mother_id, properties FROM pigeons WHERE id = $1
`

func (q *Queries) GetPigeon(ctx context.Context, id int64) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, getPigeon, id)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BirthDate,
		&i.Sex,
		&i.FatherID,
		&i.MotherID,
		&i.Properties,
	)
	return i, err
}

const getPigeonChildrenAsFather = `-- name: GetPigeonChildrenAsFather :many
SELECT c.id, c.name, c.created_at, c.birth_date, c.sex, c.father_id, c.mother_id, c.properties FROM pigeons p
INNER JOIN pigeons c ON c.father_id = p.id
WHERE p.id = $1
`

func (q *Queries) GetPigeonChildrenAsFather(ctx context.Context, id int64) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, getPigeonChildrenAsFather, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BirthDate,
			&i.Sex,
			&i.FatherID,
			&i.MotherID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPigeonChildrenAsMother = `-- name: GetPigeonChildrenAsMother :many
SELECT c.id, c.name, c.created_at, c.birth_date, c.sex, c.father_id, c.mother_id, c.properties FROM pigeons p
INNER JOIN pigeons c ON c.mother_id = p.id
WHERE p.id = $1
`

func (q *Queries) GetPigeonChildrenAsMother(ctx context.Context, id int64) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, getPigeonChildrenAsMother, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BirthDate,
			&i.Sex,
			&i.FatherID,
			&i.MotherID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPigeonFather = `-- name: GetPigeonFather :one
SELECT f.id, f.name, f.created_at, f.birth_date, f.sex, f.father_id, f.mother_id, f.properties FROM pigeons p
INNER JOIN pigeons f ON f.id = p.father_id
WHERE p.id = $1
`

func (q *Queries) GetPigeonFather(ctx context.Context, id int64) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, getPigeonFather, id)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BirthDate,
		&i.Sex,
		&i.FatherID,
		&i.MotherID,
		&i.Properties,
	)
	return i, err
}

const getPigeonMother = `-- name: GetPigeonMother :one
SELECT m.id, m.name, m.created_at, m.birth_date, m.sex, m.father_id, m.mother_id, m.properties FROM pigeons p
INNER JOIN pigeons m ON m.id = p.mother_id
WHERE p.id = $1
`

func (q *Queries) GetPigeonMother(ctx context.Context, id int64) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, getPigeonMother, id)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BirthDate,
		&i.Sex,
		&i.FatherID,
		&i.MotherID,
		&i.Properties,
	)
	return i, err
}

const getPigeonSex = `-- name: GetPigeonSex :one
SELECT sex FROM pigeons WHERE id = $1
`

func (q *Queries) GetPigeonSex(ctx context.Context, id int64) (*string, error) {
	row := q.db.QueryRowContext(ctx, getPigeonSex, id)
	var sex *string
	err := row.Scan(&sex)
	return sex, err
}

const listPigeons = `-- name: ListPigeons :many
SELECT id, name, created_at, birth_date, sex, father_id, mother_id, properties FROM pigeons ORDER BY id
`

func (q *Queries) ListPigeons(ctx context.Context) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, listPigeons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BirthDate,
			&i.Sex,
			&i.FatherID,
			&i.MotherID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPigeonsByPropertiesContains = `-- name: ListPigeonsByPropertiesContains :many
SELECT id, name, created_at, birth_date, sex, father_id, mother_id, properties FROM pigeons
WHERE properties @> $1::jsonb
ORDER BY id
`

func (q *Queries) ListPigeonsByPropertiesContains(ctx context.Context, filter json.RawMessage) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, listPigeonsByPropertiesContains, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BirthDate,
			&i.Sex,
			&i.FatherID,
			&i.MotherID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPigeonsByPropertyKey = `-- name: ListPigeonsByPropertyKey :many
SELECT id, name, created_at, birth_date, sex, father_id, mother_id, properties FROM pigeons
WHERE properties ? $1::text
ORDER BY id
`

func (q *Queries) ListPigeonsByPropertyKey(ctx context.Context, key string) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, listPigeonsByPropertyKey, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BirthDate,
			&i.Sex,
			&i.FatherID,
			&i.MotherID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPigeonsByPropertyValue = `-- name: ListPigeonsByPropertyValue :many
SELECT id, name, created_at, birth_date, sex, father_id, mother_id, properties FROM pigeons
WHERE properties ->> $1::text = $2::text
ORDER BY id
`

type ListPigeonsByPropertyValueParams struct {
	Key   string
	Value string
}

func (q *Queries) ListPigeonsByPropertyValue(ctx context.Context, arg ListPigeonsByPropertyValueParams) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, listPigeonsByPropertyValue, arg.Key, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BirthDate,
			&i.Sex,
			&i.FatherID,
			&i.MotherID,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePigeon = `-- name: UpdatePigeon :one
UPDATE pigeons
SET
    name        = COALESCE($1, name),
    birth_date  = CASE WHEN $2::bool THEN $3 ELSE birth_date END,
    sex         = CASE WHEN $4::bool THEN $5 ELSE sex END,
    properties  = CASE WHEN $6::bool THEN $7 ELSE properties END
WHERE id = $8
RETURNING id, name, created_at, birth_date, sex, father_id, mother_id, properties
`

type UpdatePigeonParams struct {
	Name          *string
	SetBirthDate  bool
	BirthDate     *time.Time
	SetSex        bool
	Sex           *string
	SetProperties bool
	Properties    *json.RawMessage
	ID            int64
}

func (q *Queries) UpdatePigeon(ctx context.Context, arg UpdatePigeonParams) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, updatePigeon,
		arg.Name,
		arg.SetBirthDate,
		arg.BirthDate,
		arg.SetSex,
		arg.Sex,
		arg.SetProperties,
		arg.Properties,
		arg.ID,
	)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BirthDate,
		&i.Sex,
		&i.FatherID,
		&i.MotherID,
		&i.Properties,
	)
	return i, err
}

const updatePigeonFather = `-- name: UpdatePigeonFather :exec
UPDATE pigeons
SET father_id = $1
WHERE id = $2
`

type UpdatePigeonFatherParams struct {
	FatherID sql.NullInt64
	ID       int64
}

func (q *Queries) UpdatePigeonFather(ctx context.Context, arg UpdatePigeonFatherParams) error {
	_, err := q.db.ExecContext(ctx, updatePigeonFather, arg.FatherID, arg.ID)
	return err
}

const updatePigeonMother = `-- name: UpdatePigeonMother :exec
UPDATE pigeons
SET mother_id = $1
WHERE id = $2
`

type UpdatePigeonMotherParams struct {
	MotherID sql.NullInt64
	ID       int64
}

func (q *Queries) UpdatePigeonMother(ctx context.Context, arg UpdatePigeonMotherParams) error {
	_, err := q.db.ExecContext(ctx, updatePigeonMother, arg.MotherID, arg.ID)
	return err
}
