// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/reinielfc/pitchondb/api/internal/pigeon"
	mock "github.com/stretchr/testify/mock"
)

// NewQueryService creates a new instance of QueryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryService {
	mock := &QueryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// QueryService is an autogenerated mock type for the QueryService type
type QueryService struct {
	mock.Mock
}

type QueryService_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryService) EXPECT() *QueryService_Expecter {
	return &QueryService_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type QueryService
func (_mock *QueryService) List(ctx context.Context, f pigeon.ListFilter) ([]pigeon.Summary, int, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []pigeon.Summary
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pigeon.ListFilter) ([]pigeon.Summary, int, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pigeon.ListFilter) []pigeon.Summary); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pigeon.Summary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pigeon.ListFilter) int); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, pigeon.ListFilter) error); ok {
		r2 = returnFunc(ctx, f)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// QueryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type QueryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f pigeon.ListFilter
func (_e *QueryService_Expecter) List(ctx any, f any) *QueryService_List_Call {
	return &QueryService_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *QueryService_List_Call) Run(run func(ctx context.Context, f pigeon.ListFilter)) *QueryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pigeon.ListFilter
		if args[1] != nil {
			arg1 = args[1].(pigeon.ListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *QueryService_List_Call) Return(summarys []pigeon.Summary, n int, err error) *QueryService_List_Call {
	_c.Call.Return(summarys, n, err)
	return _c
}

func (_c *QueryService_List_Call) RunAndReturn(run func(ctx context.Context, f pigeon.ListFilter) ([]pigeon.Summary, int, error)) *QueryService_List_Call {
	_c.Call.Return(run)
	return _c
}
