// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"
)

type Pigeon struct {
	ID         int64
	Name       string
	CreatedAt  time.Time
	BandNumber sql.NullString
	BirthDate  sql.NullTime
	Sex        sql.NullString
}
