// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pigeons.sql

package repository

import (
	"context"
)

const createPigeon = `-- name: CreatePigeon :one
INSERT INTO pigeons (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreatePigeon(ctx context.Context, name string) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, createPigeon, name)
	var i Pigeon
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getPigeon = `-- name: GetPigeon :one
SELECT id, name, created_at FROM pigeons WHERE id = $1
`

func (q *Queries) GetPigeon(ctx context.Context, id int64) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, getPigeon, id)
	var i Pigeon
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listPigeons = `-- name: ListPigeons :many
SELECT id, name, created_at FROM pigeons ORDER BY id
`

func (q *Queries) ListPigeons(ctx context.Context) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, listPigeons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
