// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreatePigeon(ctx context.Context, arg CreatePigeonParams) (CreatePigeonRow, error)
	DeletePigeon(ctx context.Context, id int64) error
	GetPigeon(ctx context.Context, id int64) (GetPigeonRow, error)
	ListPigeons(ctx context.Context) ([]ListPigeonsRow, error)
	UpdatePigeon(ctx context.Context, arg UpdatePigeonParams) (UpdatePigeonRow, error)
}

var _ Querier = (*Queries)(nil)
