// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CreatePigeon(ctx context.Context, name string) (Pigeon, error)
	GetPigeon(ctx context.Context, id int64) (Pigeon, error)
	ListPigeons(ctx context.Context) ([]Pigeon, error)
}

var _ Querier = (*Queries)(nil)
