// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Pigeon struct {
	ID            uuid.UUID
	Name          sql.NullString
	RingNumber    sql.NullString
	Sex           string
	SexConfidence sql.NullString
	Status        string
	AcquiredDate  sql.NullTime
	AcquiredVia   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type PigeonSummary struct {
	ID            uuid.UUID
	Name          sql.NullString
	RingNumber    sql.NullString
	Sex           string
	SexConfidence sql.NullString
	Status        string
	AcquiredDate  sql.NullTime
	AcquiredVia   string
	CreatedAt     time.Time
}
