// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pigeons.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countPigeons = `-- name: CountPigeons :one
SELECT COUNT(*) FROM pigeons
`

func (q *Queries) CountPigeons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPigeons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findPigeonByID = `-- name: FindPigeonByID :one
SELECT id, name, ring_number, sex, sex_confidence, status, acquired_date, acquired_via, created_at, updated_at FROM pigeons WHERE id = $1
`

func (q *Queries) FindPigeonByID(ctx context.Context, id uuid.UUID) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, findPigeonByID, id)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RingNumber,
		&i.Sex,
		&i.SexConfidence,
		&i.Status,
		&i.AcquiredDate,
		&i.AcquiredVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPigeons = `-- name: ListPigeons :many
SELECT id, name, ring_number, sex, sex_confidence, status, acquired_date, acquired_via, created_at
FROM pigeon_summaries
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPigeonsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPigeons(ctx context.Context, arg ListPigeonsParams) ([]PigeonSummary, error) {
	rows, err := q.db.QueryContext(ctx, listPigeons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PigeonSummary
	for rows.Next() {
		var i PigeonSummary
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RingNumber,
			&i.Sex,
			&i.SexConfidence,
			&i.Status,
			&i.AcquiredDate,
			&i.AcquiredVia,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPigeon = `-- name: UpsertPigeon :one
INSERT INTO pigeons (id, name, ring_number, sex, sex_confidence, status, acquired_date, acquired_via, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    ring_number = EXCLUDED.ring_number,
    sex = EXCLUDED.sex,
    sex_confidence = EXCLUDED.sex_confidence,
    status = EXCLUDED.status,
    acquired_date = EXCLUDED.acquired_date,
    acquired_via = EXCLUDED.acquired_via,
    updated_at = now()
RETURNING id, name, ring_number, sex, sex_confidence, status, acquired_date, acquired_via, created_at, updated_at
`

type UpsertPigeonParams struct {
	ID            uuid.UUID
	Name          sql.NullString
	RingNumber    sql.NullString
	Sex           string
	SexConfidence sql.NullString
	Status        string
	AcquiredDate  sql.NullTime
	AcquiredVia   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpsertPigeon(ctx context.Context, arg UpsertPigeonParams) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, upsertPigeon,
		arg.ID,
		arg.Name,
		arg.RingNumber,
		arg.Sex,
		arg.SexConfidence,
		arg.Status,
		arg.AcquiredDate,
		arg.AcquiredVia,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RingNumber,
		&i.Sex,
		&i.SexConfidence,
		&i.Status,
		&i.AcquiredDate,
		&i.AcquiredVia,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
