// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountPigeons(ctx context.Context) (int64, error)
	DeletePigeon(ctx context.Context, id uuid.UUID) error
	FindPigeonByID(ctx context.Context, id uuid.UUID) (Pigeon, error)
	ListPigeons(ctx context.Context, arg ListPigeonsParams) ([]PigeonSummary, error)
	UpsertPigeon(ctx context.Context, arg UpsertPigeonParams) (Pigeon, error)
}

var _ Querier = (*Queries)(nil)
