// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Pigeon struct {
	ID         int64
	Name       string
	CreatedAt  time.Time
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
	FatherID   sql.NullInt64
	MotherID   sql.NullInt64
}

type PigeonTag struct {
	PigeonID int64
	TagID    int64
}

type Tag struct {
	ID   int64
	Name string
}
