// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pigeons.sql

package db

import (
	"context"
	"time"
)

const createPigeon = `-- name: CreatePigeon :one
INSERT INTO pigeons (name, band_number, birth_date, sex)
VALUES ($1, $2, $3, $4)
RETURNING id, name, created_at, band_number, birth_date, sex
`

type CreatePigeonParams struct {
	Name       string
	BandNumber *string
	BirthDate  *time.Time
	Sex        *string
}

func (q *Queries) CreatePigeon(ctx context.Context, arg CreatePigeonParams) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, createPigeon,
		arg.Name,
		arg.BandNumber,
		arg.BirthDate,
		arg.Sex,
	)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BandNumber,
		&i.BirthDate,
		&i.Sex,
	)
	return i, err
}

const deletePigeon = `-- name: DeletePigeon :exec
DELETE FROM pigeons WHERE id = $1
`

func (q *Queries) DeletePigeon(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePigeon, id)
	return err
}

const getPigeon = `-- name: GetPigeon :one
SELECT id, name, created_at, band_number, birth_date, sex FROM pigeons WHERE id = $1
`

func (q *Queries) GetPigeon(ctx context.Context, id int64) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, getPigeon, id)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BandNumber,
		&i.BirthDate,
		&i.Sex,
	)
	return i, err
}

const listPigeons = `-- name: ListPigeons :many
SELECT id, name, created_at, band_number, birth_date, sex FROM pigeons ORDER BY id
`

func (q *Queries) ListPigeons(ctx context.Context) ([]Pigeon, error) {
	rows, err := q.db.QueryContext(ctx, listPigeons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pigeon
	for rows.Next() {
		var i Pigeon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.BandNumber,
			&i.BirthDate,
			&i.Sex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pigeonExists = `-- name: PigeonExists :one
SELECT EXISTS (
    SELECT 1
    FROM pigeons
    WHERE id = $1
)
`

func (q *Queries) PigeonExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, pigeonExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePigeon = `-- name: UpdatePigeon :one
UPDATE pigeons
SET
    name        = COALESCE($1, name),
    band_number = CASE WHEN $2::bool THEN $3 ELSE band_number END,
    birth_date  = CASE WHEN $4::bool THEN $5 ELSE birth_date END,
    sex         = CASE WHEN $6::bool THEN $7 ELSE sex END
WHERE id = $8
RETURNING id, name, created_at, band_number, birth_date, sex
`

type UpdatePigeonParams struct {
	Name          *string
	SetBandNumber bool
	BandNumber    *string
	SetBirthDate  bool
	BirthDate     *time.Time
	SetSex        bool
	Sex           *string
	ID            int64
}

func (q *Queries) UpdatePigeon(ctx context.Context, arg UpdatePigeonParams) (Pigeon, error) {
	row := q.db.QueryRowContext(ctx, updatePigeon,
		arg.Name,
		arg.SetBandNumber,
		arg.BandNumber,
		arg.SetBirthDate,
		arg.BirthDate,
		arg.SetSex,
		arg.Sex,
		arg.ID,
	)
	var i Pigeon
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.BandNumber,
		&i.BirthDate,
		&i.Sex,
	)
	return i, err
}
