// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddPigeonTag(ctx context.Context, arg AddPigeonTagParams) error
	ClearPigeonTags(ctx context.Context, pigeonID int64) error
	ClearUnusedTags(ctx context.Context) error
	CreatePigeon(ctx context.Context, arg CreatePigeonParams) (Pigeon, error)
	DeletePigeon(ctx context.Context, id int64) error
	GetPigeon(ctx context.Context, id int64) (Pigeon, error)
	GetPigeonTags(ctx context.Context, pigeonID int64) ([]string, error)
	ListPigeons(ctx context.Context) ([]Pigeon, error)
	ListTags(ctx context.Context) ([]string, error)
	PigeonExists(ctx context.Context, id int64) (bool, error)
	RemovePigeonTag(ctx context.Context, arg RemovePigeonTagParams) error
	UpdatePigeon(ctx context.Context, arg UpdatePigeonParams) (Pigeon, error)
	UpsertTag(ctx context.Context, name string) (Tag, error)
}

var _ Querier = (*Queries)(nil)
