with-expecter: true
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  pitch-on-db/repos:
    config:
      all: true
      dir: services/mocks
      outpkg: mocks
