structname: "{{.InterfaceName}}"
filename: "{{.InterfaceFile | base}}"
pkgname: mocks

packages:
  github.com/reinielfc/pitchondb/apps/api/internal/pigeon:
    config:
      dir: "{{.InterfaceDir}}/mocks"
    interfaces:
      Repository:
      QueryService:
