# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GO: '{{.GO | default "go"}}'

  OPENAPI_SPEC: '{{.OPENAPI_SPEC | default "./openapi.yml"}}'

  BUILD_LDFLAGS: >-
    -s -w
    -X main.version={{.BUILD_VERSION | default "dev"}}
    -X main.commit={{.BUILD_COMMIT | default "unknown"}}
    -X main.buildTime={{.BUILD_TIMESTAMP | default "unknown"}}
  BUILD_FLAGS: -ldflags {{.BUILD_LDFLAGS|q}}

  SERVICE_CMD: ./cmd/service
  SERVICE_RUN: "{{.GO}} run {{.BUILD_FLAGS}} {{.SERVICE_CMD}}"
  SERVICE_BUILD_FMT: "{{.GO}} build {{.BUILD_FLAGS}} -o %s {{.SERVICE_CMD}}"

  OUTPUT:
    map:
      BUILD: "./bin/service"
      DEV: "./tmp/main"
      TEST_COVER: "./coverage.out"

env:
  SERVICE_POSTGRES_HOST: '{{.POSTGRES_HOST | default "localhost"}}'
  SERVICE_POSTGRES_PORT: '{{.POSTGRES_PORT | default "5432"}}'
  SERVICE_POSTGRES_USER: '{{.POSTGRES_USER | default "pitchondb"}}'
  SERVICE_POSTGRES_PASSWORD: '{{.POSTGRES_PASSWORD | default "pitchondb"}}'
  SERVICE_POSTGRES_DB: '{{.POSTGRES_DB | default "pitchondb"}}'
  SERVICE_POSTGRES_SSLMODE: '{{.POSTGRES_SSLMODE  | default "disable"}}'

tasks:
  # Development Environment

  sync:
    desc: Synchronize dependencies
    cmd: "{{.GO}} mod tidy"

  init:dotenv:development:
    internal: true
    vars:
      ENV_FILE_NAME: ".env.development"
      ENV_FILE: '{{relPath "." .ENV_FILE_NAME}}'
      ENV_EXAMPLE_FILE: >-
        {{- $name := printf "%s.example" .ENV_FILE_NAME -}}
        {{relPath "." $name}}
    sources: ["{{.ENV_FILE}}"]
    generates: ["{{.ENV_EXAMPLE_FILE}}"]
    cmd: "cp -v {{.ENV_EXAMPLE_FILE|q}} {{.ENV_FILE|q}}"

  # Build / Run

  build:
    desc: Compile service binary
    sources: ["**/*.go", go.mod, { exclude: "**/*_test.go" }]
    generates: ["{{.OUTPUT.BUILD}}"]
    cmd: "{{printf .SERVICE_BUILD_FMT .OUTPUT.BUILD}}"

  run:
    desc: Run service locally
    cmd: "{{.SERVICE_RUN}}"

  dev:
    desc: Run service with live reload
    deps: [{ task: init:dotenv:development }]
    vars:
      CONFIG: ".air.toml"
      BUILD_CMD: "{{printf .SERVICE_BUILD_FMT .OUTPUT.DEV}}"
    generates: ["{{.OUTPUT.DEV}}"]
    cmd: "{{.GO}} tool air -c {{.CONFIG}} --build.cmd={{.BUILD_CMD|q}}"

  doc:
    desc: Run godoc server
    vars:
      PACKAGE: "golang.org/x/pkgsite/cmd/pkgsite@latest"
      HOST: '{{.HOST | default "localhost"}}'
      PORT: 6060
    cmd: "{{.GO}} run {{.PACKAGE}} -http={{.HOST}}:{{.PORT}}"

  healthcheck:
    desc: Perform health check on service
    vars: { RETRIES: 3, INTERVAL: 3s }
    cmd: "{{.SERVICE_RUN}} healthcheck -r {{.RETRIES}} -i {{.INTERVAL}}"

  # Quality Assurance

  test:
    desc: Run unit tests
    cmd: "{{.GO}} test -v -race -count=1 ./..."

  test-cover:
    desc: Run unit tests with coverage report
    generates: ["{{.OUTPUT.TEST_COVER}}"]
    cmds:
      - "{{.GO}} test -v -race -coverprofile={{.OUTPUT.TEST_COVER}} ./..."
      - "{{.GO}} tool cover -func={{.OUTPUT.TEST_COVER}}"

  lint:
    desc: Run linter
    cmd: "golangci-lint run ./..."

  format:
    desc: Format code
    sources: ["**/*.go"]
    cmds:
      - "{{.GO}} fmt ./..."
      - "{{.GO}} tool goimports -w ."

  vet:
    desc: Vet code
    cmd: "{{.GO}} vet ./..."

  # Code Generation

  gen:
    desc: Generate code
    sources: ["**/*.go"]
    generates: ["**/*_enumer.go"]
    cmd: { task: "gen:tool:enumer" }

  gen:mocks:
    desc: Generate Mocks
    vars: { CONFIG: "./.mockery.yml" }
    sources: ["**/*.go", "{{.CONFIG}}"]
    cmd: "{{.GO}} tool mockery --config={{.CONFIG}}"

  gen:spec:
    desc: OpenAPI spec
    sources: ["**/*.go"]
    generates: ["{{.OPENAPI_SPEC}}"]
    cmd: "{{.SERVICE_RUN}} openapi -o {{.OPENAPI_SPEC}}"

  gen:tool:*:
    internal: true
    desc: Generate code for the specified tool
    vars: { TOOL: "{{index .MATCH 0}}" }
    cmd: '{{.GO}} generate -x -run="go tool {{.TOOL}}" ./...'

  # Clean

  clean:
    desc: Clean build artifacts
    cmd:
      for: { var: OUTPUT, as: ARTIFACT }
      cmd: "rm -v {{.ARTIFACT|q}}"
      if: "[ -e {{.ARTIFACT}} ]"
